## Makefile by
## Christian Panse <cp@fgcz.ethz.ch> 
##
##
## 2023-10-23 
## 
## usage:
##   # for Orbitrap
##   make -f Makefile.DIANN stageinput && make -f Makefile.DIANN unzip && make -f Makefile.DIANN convert && make -f Makefile.DIANN diann && make -f Makefile.DIANN output

SHELL=/bin/bash

.SUFFIXES: .mzML .raw .csv .fasta .fas .zip .xmllint .diann .d.zip .d .diann
.PHONY : dep clean .clean.raw .clean.zip test check .check-diann .check-FASTA 

NOW               = $(shell date +"%Y-%m-%dT%H:%M:%S%:z")
RAW               = $(shell find . -type f -name "*.raw" -mtime -10)
DZIP              = $(shell find . -type f -name "*.d.zip" -mtime -10)
D                 = $(DZIP:.d.zip=.d)
MZML              = $(RAW:.raw=.mzML)
XMLLINT           = $(MZML:.mzML=.xmllint)
OUTPUTORBITRAP    = $(MZML:.mzML=.diann)
OUTPUTTIMSTOF     = $(D:.d=.diann)

MSCONVERTOPTS     = chambm/pwiz-skyline-i-agree-to-the-vendor-licenses wine msconvert --mzML --64 --zlib --filter "peakPicking true 1-"

## DIANN specific
DIANN         = /usr/diann/1.8.2_beta_8/linux/diann-1.8.1.8
DIANNFASTA    = --fasta-search --fasta /srv/www/htdocs/FASTA/fgcz_uniprot-proteome_UP000005640.fasta
DIANNDEFAULTS = --threads 64 --verbose 1 --qvalue 0.01 --matrices --predictor --met-excision --cut K*,R* --min-pep-len 6 --max-pep-len 30 --unimod4 --smart-profiling
DIANNTEMP     = $(PWD)/temp


list:
	echo $(OUTPUTTIMSTOF)
	echo $(D)
	echo $(RAW)
	echo $(MZMLCHECK)
	echo $(XMLLINT)
	echo $(OUTPUTORBITRAP)

help:
	grep "^## " Makefile

convert: $(MZML) unzip
diann: $(OUTPUTORBITRAP) $(OUTPUTTIMSTOF)

## Orbitrap workflow
.raw.mzML:
	docker run -t --network none -w ${PWD} -v ${PWD}:${PWD} -v /scratch/mzML/:/scratch/mzML/ $(MSCONVERTOPTS) $< -o /scratch/mzML && cp -v /scratch/mzML//$(shell basename $< .raw).mzML $@

## TIMSTOF workflow
.d.zip.d: 
	unzip $< -d $(shell dirname $@)

unzip: $(D)



dump/autoQC03-diann.input.txt: /srv/www/htdocs/Data2San/sync_LOGS/pfiles.txt Makefile.DIANN
	cat $< \
	  | egrep "autoQC03.*dia.*(raw|zip)$$" \
	  | tee $@ \
	  | awk -F ";" '{print $$NF}' \
	  | rsync -av --chmod=D775,F444 --files-from="-" /srv/www/htdocs/ ./dump

stageinput: dump/autoQC03-diann.input.txt



### TODO
## compose stats file for dashboard
## 1. sort input
## 2. compose file header
## 3. collect diann output from stat.tsv files
dump/autoQC03-diann.txt: dump/autoQC03-diann.input.txt Makefile.DIANN
	## 1. sort input for join cmd
	sort -t';' -k4 $<  > ../input.txt.s
	## 2. compose file header TODO(cp): running over all header is not smart
	find . -type f -name "diaqc_report.stats.tsv" -exec head -n 1 {} \; \
	| uniq \
	| tr "\t" ";" \
	| sed 's/File.Name;/File.Name;Md5;Time;Size;/' \
	> $@
	## 3. collect diann output from stat.tsv files
	find . -type f -name "diaqc_report.stats.tsv" -exec tail -n 1 {} \; \
	| sed -e 's/dump\///' -e 's/\.mzML/\.raw/' -e 's/\.d/\.d\.zip/' \
	| tr "\t" ";" \
	| sort \
	| join -t";" -1 4 -2 1 ../input.txt.s - \
	| sort -k3 -g -t';' \
	>> $@

output: dump/autoQC03-diann.txt
statistics: dump/autoQC03-diann.txt
	(cat -n $< | head -n 4  ; echo "..."; cat -n $< | tail -n 5) \
	| cut -d";" -f1,5,6,7 \
	| tr ";" "\t" 
stat: statistics


## runs DIANN
## for Bruker TIMSTOF
.d.diann:
	mkdir -p $@ $(DIANNTEMP) \
	&& nice -19 $(DIANN) $(DIANNDEFAULTS) --f $< $(DIANNFASTA) --temp $< --temp $(DIANNTEMP) --out $@/diaqc_report.tsv \
	|| mv $@ $@.$(NOW).broken

## for Thermo Fischer Scientific Orbitraps via mzML
.mzML.diann:
	mkdir -p $@ $(DIANNTEMP) \
	&& nice -19 $(DIANN) $(DIANNDEFAULTS) --f $< $(DIANNFASTA) --temp $< --temp $(DIANNTEMP) --out $@/diaqc_report.tsv \
	|| mv $@ $@.$(NOW).broken

.mzML.xmllint:
	xmllint --noout $< > $@ 

##### CLEAN
.clean-xmlllint:
	$(RM) $(XMLLINT)

.clean-mzML:
	find . -type f -name "*.mzML" -exec $(RM) -v {} \;

.clean-diann:
	# $(RM) -rfv $(OUTPUT)

check: $(XMLLINT)
clean: .clean-mzML .clean-xmllint .clean-diann
